### ISSUE TITLE
btst not decoded in 2 words mode

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#50] opened 2015-09-30 13:55 UTC
```
--- .objdump	2015-09-30 23:52:32.533237296 +1000
+++ .capstone	2015-09-30 23:52:32.643230480 +1000
@@ -5,5 +5,6 @@
 Disassembly of section .data:
 
 00000000 <.data>:
-   0:	0816 d5d6      	btst #-42,%fp@
+   0:	0816           	.short 0x0816
+   2:	d5d6           	addal %fp@,%a2
    4:	b4da           	cmpaw %a2@+,%a2
```

**Comment by emoon** [comment] 2015-09-30 14:08
hum.. what is actually %fp@ here?

**Comment by nplanel** [comment] 2015-09-30 14:27
another sample

--- .objdump	2015-10-01 00:26:22.761196877 +1000
+++ .capstone	2015-10-01 00:26:22.857860003 +1000
@@ -5,5 +5,6 @@
 Disassembly of section .data:
 
 00000000 <.data>:
-   0:	081d 7219      	btst #25,%a5@+
-   4:	ce2b           	.short 0xce2b
+   0:	081d           	.short 0x081d
+   2:	7219           	moveq #25,%d1
+   4:	ce2b           	andb %d3,%d7

**Comment by emoon** [comment] 2015-09-30 16:12
I guess it's caused by this code

https://github.com/emoon/capstone/blob/next/arch/M68K/M68Kdasm.c#L1625

only reading 1 byte instead of 2

**Comment by emoon** [comment] 2015-09-30 19:36
I actually think this is a case where objdump is wrong (again)

```C
	{d68000_btst_s       , 0xffc0, 0x0800, 0xbfb, 0xff00, 0x0000},
```

![btst_inst](https://cloud.githubusercontent.com/assets/350822/10204262/053ed64a-67bb-11e5-898a-f13520f556cd.png)

The version in capstone matches against that upper 8 bit of the second word is zero (which is indicated by the instruction) it should but if in our case this isn't matched we drop the instruction and consider it invalid.

So I guess is a definition question here if one should decode the instruction whatever is present in the second word or not.

**Comment by emoon** [comment] 2015-10-02 14:43
So should we close this one? it really depends on if we "care" about bad data in the upper 8 bits. The instruction manual states they should be zero so I would say capstone is doing the right thing here.

**Closed** 2015-10-02 17:08 UTC
